version: '3.8'

services:

  redis:
    image: "redis:alpine"
    networks:
      - my_network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  #  browser:
  #    image: selenium/standalone-chrome:latest
  #    shm_size: 2gb
  #    networks:
  #      - my_network
  #    ports:
  #      - "4444:4444"
  #      - "7900:7900"
  #    environment:
  #      NOVNC_PASSWORD: ${NOVNC_PASSWORD}
  #    logging:
      #      driver: "json-file"
      #      options:
    #        max-size: "10m"
    #        max-file: "10"


  web:
    depends_on:
      #      - browser
      - redis
    env_file:
      - .env
    build:
      context: ./
      args:
        assembling_mod: ${ASSEMBLING_MOD}
      dockerfile: web/Dockerfile
    networks:
      - my_network
    command: >
      sh -c "python init.py && gunicorn -c ./gunicorn/gunicorn.conf.py web.app:init_app"
    #    environment:
    #      BROWSER_HOST: browser
    #      BROWSER_PORT: 4444
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  bot:
    depends_on:
      - redis
      - web
    env_file:
      - .env
    build:
      context: ./
      args:
        assembling_mod: ${ASSEMBLING_MOD}
      dockerfile: bot/Dockerfile
    networks:
      - my_network
    command: >
      sh -c "python bot/app.py"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"


  nginx:
    depends_on:
      - web
      - bot
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "127.0.0.1:8008:8081"
    networks:
      - my_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  my_network:
    driver: bridge